### ISSUE TITLE
data-skip attributes from scoped variables (Tokens)

### ISSUE THREAD

**Issue by david-cooper** [soundstep/soma-template#26]
Hi,

I'm running into an issue while using repeaters within soma-template. The data-skip attribute looks like it should resolve the problems I'm encountering, but it doesn't seem to behave as I'd expect when using a boolean value set against the scope or returned from a scoped function or helper function.

Here's an example:
http://plnkr.co/edit/BGmNq8RQhu2pX3HHeMa7?p=preview

From what I can see, none of the {{age}} values should be rendered as they are both set with an active data-skip attribute. However data-skip only seems to function when given "true".

Thanks for your time.

Dave

**Comment by soundstep** [comment]
`data-skip` means it is skipping the interpolation, so it is normal it doesn't work if you add a token to it:
https://github.com/soundstep/soma-template/blob/dcd452c881aada460d67354e08e98e439fb6b33c/build/soma-template.js#L536
It was not meant to skip the children of a node, but the actual node itself as well.
In other words, it can't be interpolated.

Instead of skipping, maybe you can try to interpolate a different data. If you really need this dynamic, you can still change the DOM manually before rendering the template.

```
element.setAttribute('data-skip', shouldSkip);
template.render()
```

You can also access to the virtual node from the template:

```
var node = template.getNode(document.getElementById('a-node'));
node.skip = false;
template.render() // or node.render()
```

http://soundstep.github.io/soma-template/#template-engine-process

**Comment by david-cooper** [comment]
Hi,

Thanks for the update on this - I can see the data-skip working when I add it in manually, this seems like it'll be handy in test environments where I want to just skip sections which I know are OK.

I've worked around my original problem, so I no longer need data-skip working as mentioned in the initial comment, so I'll close this issue.

I did notice some strange behavior when adding the data-skip="true" attribute to an element - it seems that my child nodes started experiencing errors saying unable to read property "attributes" of undefined - however that could also be due to my template layout.

Cheers.
